### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by orandaadnaro** [freahs/node-red-contrib-node-tradfri#11]
Im using node red v0.19.1 on home assistant

when I try to install node-red-contrib-node-tradfri
it fails with this error 

22/09/2018, 09:27:57
msg : string[5300]
string[5300]
npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)

> node-aead-crypto@1.1.6 install /config/node-red/node_modules/node-aead-crypto
> node lib/install.js

running default installation script

> node-aead-crypto@1.1.6 install:default /config/node-red/node_modules/node-aead-crypto
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/AlCalzone/node-aead-crypto/releases/download/v1.1.6/node-v57-linux-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-aead-crypto@1.1.6 and node@8.11.4 (node-v57 ABI, musl) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack...

not sure what it means

**Comment by lightenup** [comment]
I have the same issue, but I´m using version  v0.19.4 of Node Red on Home Assistant.

**Comment by xopr** [comment]
[flavorplus' fork](https://github.com/flavorplus/node-red-contrib-node-tradfri) and [my own fork](https://github.com/xopr/node-red-contrib-node-tradfri) were recently updated with the latest (dev) node modules; this might fix the aforementioned problems.

Note that the installation via NPM is slightly different (and mentioned in our READMEs).
